# Generated by Django 4.0.5 on 2022-06-26 10:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0002_remove_dish_restaurant_dish_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['restaurant'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
