# Generated by Django 4.0.5 on 2022-06-29 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dish', '0003_alter_dish_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'ordering': ['restaurant', 'title'], 'verbose_name': 'Блюдо', 'verbose_name_plural': 'Блюда'},
        ),
    ]
