# Generated by Django 4.0.5 on 2023-01-21 18:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0007_historicalrestaurants_historicalcategory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dish', '0004_alter_dish_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDish',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название блюда')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cover', models.TextField(max_length=100, verbose_name='Фотография')),
                ('weight', models.IntegerField(verbose_name='Вес/количество (граммы)')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('restaurant', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='restaurant.restaurants', verbose_name='Ресторан')),
            ],
            options={
                'verbose_name': 'historical Блюдо',
                'verbose_name_plural': 'historical Блюда',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
