# Generated by Django 4.0.5 on 2022-07-02 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('discount_coupons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupons',
            name='users',
            field=models.ManyToManyField(to='auth.group', verbose_name='Пользователи'),
        ),
        migrations.AlterField(
            model_name='coupons',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Название акции'),
        ),
    ]
