# Generated by Django 4.0.5 on 2022-07-02 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount_coupons', '0002_coupons_users_alter_coupons_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupons',
            name='users',
        ),
    ]
