# Generated by Django 4.0.5 on 2022-06-26 00:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_category_alter_restaurants_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurants',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='restaurant.category', verbose_name='Категория ресторана'),
        ),
    ]
