# Generated by Django 4.0.5 on 2022-07-03 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_alter_category_options_alter_restaurants_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='logo',
            field=models.ImageField(null=True, upload_to='filters', verbose_name='Логотип'),
        ),
    ]
